name: CI for product-review-api

on:
  push:
    branches:
      - main
    paths:
      - 'services/product-review-api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        export sha_short=$(git rev-parse --short ${GITHUB_SHA})
        docker build -t ${{ secrets.DOCKER_USERNAME }}/product-review-api:$sha_short .
        docker push ${{ secrets.DOCKER_USERNAME }}/product-review-api:$sha_short